# 2022-11-09

In [1]:
import numpy as np

In [3]:
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])

print(py_list)
print(np_array)

[1, 2, 3, 4]
[1 2 3 4]


In [5]:
# Np array with different types

a = np.array([1, 2, 3, 4], dtype=np.float64)
a

array([1., 2., 3., 4.])

In [10]:
# 2d array

a = np.array([[1, 2, 3], [3, 4, 5]])
print(a, a.ndim, a.shape)

[[1 2 3]
 [3 4 5]] 2 (2, 3)


In [11]:
# 3d array

a = np.array([[[1, 2, 3], [3, 4, 5]]])
print(a, a.ndim, a.shape)

[[[1 2 3]
  [3 4 5]]] 3 (1, 2, 3)


In [12]:
# Check array type

print(np.array([1, 2, 3], dtype=np.float32).dtype)
print(np.array([1, 2, 3], dtype=np.int32).dtype)

float32
int32


In [15]:
# Check array size

print(np.array([1, 2, 3], dtype=np.float32).itemsize)
print(np.array([[1, 2, 3], [1, 2, 3]], dtype=np.float32).itemsize)
print(np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]], dtype=np.float32).itemsize)

4
4
4


In [17]:
# Check size in memory

print(np.array([1, 2, 3], dtype=np.int8).nbytes)
print(np.array([1, 2, 3], dtype=np.int64).nbytes)

3
24


In [18]:
# Check size in memory

print(np.ones((1000, 1000), dtype=np.int8).nbytes)
print(np.ones((1000, 1000), dtype=np.int64).nbytes)

1000000
8000000


In [27]:
# Array access
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])
print(py_list[0])
print(np_array[0])

py_list = [[1, 2], [3, 4], [5, 6]]
np_array = np.array(py_list)

print(py_list[0][0])
print(np_array[0,0])


print(np_array[:,0])
print(np_array[0,:])

1
1
1
1
[1 3 5]
[1 2]


In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[:,1:-1])
print(a[-2:-1,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[5 6]]


In [39]:
# Access and change 

zeros = np.zeros((5, 5))
print(zeros)
ones = np.ones((3, 3))
print(ones)

print(zeros[1:-1, 1:-1])

zeros[1:-1, 1:-1] = ones

print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
# This does not work

filler = [[1, 1,], [1, 1], [1, 1]]

zeros[1:-1, 1:-1] = filler

ValueError: could not broadcast input array from shape (3,2) into shape (3,3)

In [42]:
# Initialize arrays with pre-filled 0s

np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# Initialize arrays with pre-filled 1s

np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
# Filling arrays

empty = np.ndarray((2, 2))
print(empty)
empty.fill(10)
print(empty)

print(np.full((2, 2), 10))

[[10. 10.]
 [10. 10.]]
[[10. 10.]
 [10. 10.]]
[[10 10]
 [10 10]]


In [54]:
%%time

a = np.ndarray((100000, 100000))
a.fill(10)

CPU times: user 2.18 s, sys: 6.35 s, total: 8.54 s
Wall time: 15.3 s


In [55]:
%%time

a = np.full((100000, 100000), 10)

CPU times: user 2.21 s, sys: 7.11 s, total: 9.33 s
Wall time: 14.2 s


In [60]:
a = np.array([[1, 2, 3, 4], [1, 2, 4, 6]])

print(np.full_like(a, 10))
print(np.ones_like(a))
print(np.zeros_like(a))

[[10 10 10 10]
 [10 10 10 10]]
[[1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]]


In [61]:
# Intialize random array with random numbers (0-1)

np.random.rand(5, 5)

array([[0.14761005, 0.54168113, 0.28468527, 0.480612  , 0.7643192 ],
       [0.09610459, 0.84164955, 0.22714148, 0.20966886, 0.5131193 ],
       [0.9058544 , 0.90874936, 0.11014788, 0.21752583, 0.37849715],
       [0.55233713, 0.29823378, 0.34772667, 0.39243074, 0.76298306],
       [0.39273132, 0.68211964, 0.87870896, 0.74252352, 0.72292411]])

In [74]:
# Intialize random array with random numbers (with set range)

print(np.random.randint(1, 7, size=(10,)))
print(np.random.randint(1, 3, size=(16,)))

print(np.mean(np.random.randint(0, 2, size=(10000,))))

[5 5 4 1 3 1 5 6 5 4]
[1 2 1 2 2 1 2 1 2 2 1 2 1 2 1 1]
0.49993326


In [75]:
# Identity matrix

np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [76]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
# Repeat

a = np.array([[1, 2, 3, 4, 5]])
print(a)
print(np.repeat(a, 3, axis=0))
print(np.repeat(a, 3, axis=1))

[[1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]]


In [81]:
# Copy stuff

a = np.array([1, 2, 3])
b = a
b[0] = 10
print(b)
print(a)

# RIGHT WAY!
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 10
print(b)
print(a)


[10  2  3]
[10  2  3]
[10  2  3]
[1 2 3]


In [83]:
# Maths

a = np.array([1, 2, 3, 5, 6])
print(a + 1)

[2 3 4 6 7]


In [84]:
a = np.array([1, 2, 3, 5, 6])
print(a - 1)

[0 1 2 4 5]


In [122]:
a = np.array([1, 2, 3, 5, 6])
print(a * 3)

[ 3  6  9 15 18]


In [123]:
print(a > 2)

[False False  True  True  True]


In [89]:
a = np.array([1, 2, 3, 5, 6])
print(a.dtype)
print(a / 3)
print((a / 3).dtype)

int64
[0.33333333 0.66666667 1.         1.66666667 2.        ]
float64


In [91]:
b = np.array([2, 2, 4, 5, 6])
print(a + b)


[ 3  4  7 10 12]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [92]:
b = np.array([2, 2, 4, 5, 6])
print(a * b)

[ 2  4 12 25 36]


In [93]:
b = np.array([2, 2, 4, 5, 6])
print(a / b)

[0.5  1.   0.75 1.   1.  ]


In [94]:
b = np.array([2, 2, 4, 5, 6])
print(a ** b)

[    1     4    81  3125 46656]


In [95]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ,  0.28366219,  0.96017029])

In [100]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(a, a.shape)

b = np.array([[1, 2], [3, 4], [4, 6], [4, 5]])
print(b, b.shape)

print(a.dot(b))

[[1 2 3 4]
 [1 2 3 4]] (2, 4)
[[1 2]
 [3 4]
 [4 6]
 [4 5]] (4, 2)
[[35 48]
 [35 48]]


In [104]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(a, a.shape)

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b, b.shape)

print(a.dot(b.T))

[[1 2 3 4]
 [1 2 3 4]] (2, 4)
[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[30 70]
 [30 70]]


In [105]:
# Find the determinant

a = np.identity(3)
np.linalg.det(a)

1.0

In [115]:
a = np.random.randint(0, 2, size=(10,10))
print(a)
print("mean", np.mean(a))
print("min", np.min(a))
print("max", np.max(a))
print("sum", np.sum(a, axis=1))
print("sum", np.sum(a, axis=0))

[[1 0 1 1 0 0 1 0 0 0]
 [0 0 1 1 1 1 0 0 1 0]
 [0 1 0 1 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 0 1]
 [1 1 0 0 0 0 0 1 0 1]
 [0 0 1 1 0 0 1 0 0 0]
 [0 1 1 0 1 0 0 0 1 0]
 [1 0 1 1 1 0 1 1 1 0]
 [0 1 1 0 1 0 0 0 1 1]]
mean 0.42
min 0
max 1
sum [4 5 6 0 4 4 3 4 7 5]
sum [3 4 7 5 5 2 5 3 5 3]


In [116]:
# Convert to list

a = np.random.randint(0, 2, size=(10,10))

sum_arr = np.sum(a, axis=1)

sum_arr.tolist()

[5, 4, 6, 4, 7, 5, 7, 4, 5, 6]

In [120]:
# Stacking arrays

a = ([1, 2, 3, 4])
b = ([12, 22, 32, 42])

print(np.hstack((a, b)))
print(np.hstack((a, b, a)))

print(np.vstack((a, b)))
print(np.vstack((a, b, a)))

[ 1  2  3  4 12 22 32 42]
[ 1  2  3  4 12 22 32 42  1  2  3  4]
[[ 1  2  3  4]
 [12 22 32 42]]
[[ 1  2  3  4]
 [12 22 32 42]
 [ 1  2  3  4]]


In [125]:
# Read from file

filedata = np.genfromtxt("data_np.txt", delimiter=",")
print(filedata)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [132]:
# Reshaping

filedata = np.genfromtxt("data_np.txt", delimiter=",")
print(filedata.reshape(3, 3))
print(filedata.reshape(1, 3, 3))


a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(a.reshape(2, 3, 2))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [141]:
import sys

# Saving and zipping stuff

a = np.ones((1000, 1000))
b = np.zeros((1000, 1000))

with open("np_data.npz", "wb") as f:
    np.savez(f, ones=a, zeros=b)

with open("np_data.txt", "w") as f:
    np.savetxt(f, a)


with open("np_data.npz", "rb") as f:
    arr = np.load(f)

    print(sys.getsizeof(arr))
    print(sys.getsizeof(arr["ones"]))

48
8000128
