# 2022-11-07

In [ ]:
from pydantic import BaseModel

In [5]:
class Person(BaseModel):
    name: str
    lastname: str
    age: int

In [6]:
p1 = Person(name="Dominykas", lastname="Seputis", age=42)

In [10]:
p1.dict()

{'name': 'Dominykas', 'lastname': 'Seputis', 'age': 42}

In [11]:
Person(name="Dominykas", lastname="Seputis", age="42").dict()

{'name': 'Dominykas', 'lastname': 'Seputis', 'age': 42}

In [12]:
Person(name="Dominykas", lastname="Seputis", age="keturiasdesimt du").dict()

ValidationError: 1 validation error for Person
age
  value is not a valid integer (type=type_error.integer)

In [13]:
Person(name="Dominykas", lastname="Seputis", age="42", nesamone="100").dict()

{'name': 'Dominykas', 'lastname': 'Seputis', 'age': 42}

In [18]:
def div(a: int, b: int) -> int:
    return int(a / b)

def div(a: int, b: int) -> int:
    try:
        return int(a / b)
    except ZeroDivisionError:
        return 0

def div(a: int, b: int) -> int:
    if b != 0:
        return int(a / b)
    return 0

In [19]:
div(10, 0)

0

In [21]:
import requests

from bs4 import BeautifulSoup

In [40]:
res = requests.get("https://www.knygos.lt/lt/knygos/vasaros-romanas/")

In [41]:
soup = BeautifulSoup(res.content, "html.parser")

In [47]:
soup.find("div", class_="swiper-slide").find("img")

<img src="https://thumb.knygos-static.lt/z-7bZA6TGfGgxWGXFu1Kgyq-Xs0=/fit-in/0x800/images/books/2692030/1656409449_Vasaros_romanas_72max.jpg">
</img>

# Numpy

In [53]:
import numpy as np

In [55]:
a = [1, 2, 3, 4, 5]

In [56]:
a = np.array([1, 2, 3, 4, 5])

In [63]:
np.append(a, [1, 2, 3, 4])

array([1, 2, 3, 4, 5, 1, 2, 3, 4])

In [71]:
a = [
    [1, 2, 3],
    [2, 3, 4]
]

In [72]:
for row in a:
    for i, _ in enumerate(row):
        row[i] *= 10
a

[[10, 20, 30], [20, 30, 40]]

In [68]:
a = np.array([
    [1, 2, 3],
    [2, 3, 4]
])

In [70]:
a * 10

array([[10, 20, 30],
       [20, 30, 40]])

In [102]:
N = 100000
a = [[10]*N] * N
N * N 

10000000000

In [91]:
%%time
for row in a:
    for i, _ in enumerate(row):
        row[i] *= 10

CPU times: user 174 ms, sys: 2.3 ms, total: 176 ms
Wall time: 176 ms


In [103]:
a = np.ndarray(shape=[N, N])
a.fill(10)

In [104]:
%%time
a * 10

CPU times: user 3.74 s, sys: 21.4 s, total: 25.2 s
Wall time: 1min 5s


array([[100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       ...,
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.]])

In [108]:
# fill with zeros

np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [109]:
# fill with ones

np.ones((2, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [114]:
# fill with ones

np.ones((2, 4, 5), dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [123]:
#(-32768 to 32767)
np.array([0, 200], dtype=np.int16)

array([  0, 200], dtype=int16)

In [126]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
[i for i in range(0, 10, 2)]

[0, 2, 4, 6, 8]

In [130]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [135]:
a = np.array([[1, 2, 3], [1, 2, 3]])
print(a.shape)

print(np.array([2, 3, 4, ]).shape)

(2, 3)
(3,)


In [142]:
a = np.arange(0, 10)
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [144]:
a = np.array([[1, 2, 3], [1, 2, 3]])
a.reshape(6)

array([1, 2, 3, 1, 2, 3])

In [150]:
img = np.ndarray((2, 2, 3))
img.fill(10)

np.ones_like(img)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [151]:
np.ones((100, 100, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [153]:
np.set_printoptions(threshold=300000)

np.ones((100, 3, 100))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [162]:
a = np.array([10, 10, 10])
b = np.array([5, 5, 5])

print(a + b)
print(a - b)

print(a * 10)
print(a * b)

print(a / b)

print(b % a)

print(a < 10)

[15 15 15]
[5 5 5]
[100 100 100]
[50 50 50]
[2. 2. 2.]
[5 5 5]
[False False False]


In [164]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [165]:
print(A * B)

[[2 0]
 [0 4]]


In [166]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [169]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2], [3]])

print(A.shape)
print(B.shape)

res = A.dot(B)
print(res)
print(res.shape)

(2, 2)
(2, 1)
[[5]
 [3]]
(2, 1)


In [175]:
a = [1, 2, 3]
print(sum(a))

a = np.array([1, 2, 3])
print(a.sum())

6
6


In [174]:
a = [1, 2, 3]
print(min(a))

a = np.array([1, 2, 3])
print(min(a))

1
1


In [176]:
a = [1, 2, 3]
print(max(a))

a = np.array([1, 2, 3])
print(max(a))

3
3


In [184]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.max(axis=1)) # rows
print(a.max(axis=0)) # columns

[ 5 10]
[ 6  7  8  9 10]


In [185]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.sum(axis=1)) # rows
print(a.sum(axis=0)) # columns

[15 40]
[ 7  9 11 13 15]


In [188]:
a = np.array([0, 30, 45, 60, 90])

radians_a = a * np.pi / 180

np.sin(radians_a)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [192]:
a = np.random.rand(10, 10)
print(np.mean(a))
print(np.median(a))

0.5241248735255707
0.5347684087306689


In [200]:
a = np.arange(11)**2
print(a[0])
print(a[-2])

print(a[1:3])
print(a[:11:2])
print(a[::-1])

0
81
[1 4]
[  0   4  16  36  64 100]
[100  81  64  49  36  25  16   9   4   1   0]


In [204]:
students = np.array([["Dominykas", "Tadas"], [10, 23]])
students


array([['Dominykas', 'Tadas'],
       ['10', '23']], dtype='<U21')

In [209]:
a = np.array([[100, 12, 34], [2, 4, 5]])

a.T

array([[100,   2],
       [ 12,   4],
       [ 34,   5]])

In [214]:
a = np.array([[1], [2], [4]])
print(a)
a.T

[[1]
 [2]
 [4]]


array([[1, 2, 4]])

In [221]:
a = np.arange(10)

np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [225]:
a = np.array([[1], [2], [3]])
b = np.array(([2], [3], [5]))

print(a.dot(b.T))
print(a.T.dot(b))

[[ 2  3  5]
 [ 4  6 10]
 [ 6  9 15]]
[[23]]
